language: node_js
node_js:
  - "0.12.0"
install: 
  - git status
  - npm install
  - ./node_modules/bower/bin/bower -v
  - ./node_modules/bower/bin/bower install
script: ./test
  ./node_modules/gulp/bin/gulp.js dist
